### ISSUE TITLE
APDU Command VERIFY returns 6a88

### ISSUE THREAD

**Issue by michgomo08** [FeitianSmartcardReader/FEITIAN_MOBILE_READERS#16]
Hi all,

I have a FEITIAN BR301 reader and i am trying to run the VERIFY APDU command but the result is 6a88 (Referenced data not found).

My PIN is "012345" and based on some examples my command APDU is:

`00 20 00 00 06 30 31 32 33 34 35 `

I hope the answer is 9000 but it is 6a88

I have tried both ways (Private API and PC / SC API) and the answer is the same.

This is the code for Private API:

```
String sendStr = "0020000006303132333435";

byte[] send = Utility.hexStrToBytes(sendStr);

byte[] recv = ftReader.readerXfr(0, send);

showLog("send response ---> "+Utility.bytes2HexStr(recv));
```

The result is `send response ---> 6a88`

Could someone help me solve this problem?

Thanks in advance.

**Comment by FeitianSmartcardReader** [comment]
To verify your PIN, you may need select the file first, for example, with PIV card, you may need send below commands, and more information, take a look https://www.synchrocyber.com/downloads/sp800-73-3_PART2_piv-card-applic-card-common-interface.pdf

00A4040009A00000030800001000- Select File
0020008008  3131323233333434  - Verify PIN
002c00801031323334353637383132333435363738 - Unlock  

With your card, it should have same manual as reference, please check with card vendor.

Any questions, send mail to hongbin@ftsafe.com, thanks
