### ISSUE TITLE
Is posible use PKCS#11 in Android with the BR301

### ISSUE THREAD

**Issue by jjimenez0611** [FeitianSmartcardReader/FEITIAN_MOBILE_READERS#2]
Hi I download the SDK to Android, and I try to read the smart card information with APDU codes. But I don't get good results. 

I investigate and some pages recomen use a PKCS#11 to communicate with the smart card, I download I library seek-for-android, this library includes PKCS, but I really don't know how to integrate with the BR301.... 

If someone know how to do that and can help me, I really appreciated it.

**Comment by FeitianSmartcardReader** [comment]
@jjimenez0611 please send me mail hongbin@ftsafe.com and let me know your card type, then I will find partner to help on this, thanks

**Comment by jjimenez0611** [comment]
ok perfect. I will send the email

**Comment by FeitianSmartcardReader** [comment]
Al
