### ISSUE TITLE
APDU command for read/write tags to ISO 14443-3A type NFC Tag 

### ISSUE THREAD

**Issue by ram1972** [FeitianSmartcardReader/FEITIAN_MOBILE_READERS#22]
I am using FEITIAN reader BR500 and SDK. 

What is the command to read and write tags to the card?

I can use NFC Tools iOS app to read and write tags. But when using FEITIAN sdk I need to send APDU command to read the tags written.

Please help.

**Comment by FeitianSmartcardReader** [comment]
@ram1972 you can follow the PC/SC command to send the APDU.
For example, to read Mifare tag, you will need send FFCA000000 to get UID/CSN from card.

chapter 3.2.1.3, and also you can follow the APDU manual
[R502_Mifare_1K_CARD_APDU_EN_V1.0.xls](https://github.com/FeitianSmartcardReader/FEITIAN_MOBILE_READERS/files/6615715/R502_Mifare_1K_CARD_APDU_EN_V1.0.xls)

[pcsc3_v2.01.09.pdf](https://github.com/FeitianSmartcardReader/FEITIAN_MOBILE_READERS/files/6615712/pcsc3_v2.01.09.pdf)
