### ISSUE TITLE
PCSC API always crashes in method FT_SCardListReaders() in case of mszReaders=NULL

### ISSUE THREAD

**Issue by boby1975** [FeitianSmartcardReader/FEITIAN_MOBILE_READERS#29]
According documentation

_[out] mszReaders

Multi-string that lists the card readers within the supplied reader groups. **If this value is NULL**, SCardListReaders ignores the buffer length supplied in pcchReaders, writes the length of the buffer that would have been returned if this parameter had not been NULL to pcchReaders, and returns a success code._

**Comment by FeitianSmartcardReader** [comment]
fixed in 1.0.9.4.
