### ISSUE TITLE
FT_SCardListReaderGroups: Can not find the bR301 readers

### ISSUE THREAD

**Issue by Lectem** [FeitianSmartcardReader/FEITIAN_MOBILE_READERS#33]
My card reader is one with the C18 casing bR301 and the demo application can not connect to it.
It seems that the SDK `FT_SCardListReaderGroups` is looking for devices with names starting by `FT_` or `ID_` but my reader is detected with name `FeiTian73`, which means that it is ignored.

Is there something I need to do for my reader to use the correct name ? Is this a bug with the SDK ?

Note that the Demo code is still using the version 1.0.8 of the jar, and if I try with the 1.0.9 jar, it crashes. (there is no `libFTReaderPCSC_1.0.9.a` nor `libFTReaderPCSC_1.0.9.so`).

Note that I also tried the Private API, v1.0.9, and there is the same issue.

**Comment by FeitianSmartcardReader** [comment]
![device manager](https://user-images.githubusercontent.com/9547938/150322578-86556f09-dbe9-440f-9aef-11224671c1c5.png)
Would you please have a look your firmware version? thanks

**Comment by Lectem** [comment]
Somehow I was unable to get the device recognized though USB at all (I tried several times, windows update doesn't give me any new driver, and I tried with multiple USB cables that are known to work with other devices).

I can however connect through the bluetooth driver, but the `FT_bR301_Update_Tool.exe` tool will not display the device firmware version. If I click connect, I get the following error:
![image](https://user-images.githubusercontent.com/6024225/150326787-a5596062-fc12-4afb-b691-15ce244f5460.png)

Is there another way to know the device firmware version ?

**Comment by FeitianSmartcardReader** [comment]
![image](https://user-images.githubusercontent.com/9547938/150327864-c0a341e8-5601-428d-af51-89861dc13c7a.png)
Insert reader to your PC, and press power ON button, check the device manager, and after find the hardware ID, share to us, thanks

**Comment by Lectem** [comment]
As mentioned, I couldn't get the reader working though USB, I tried with 2 different readers (same model) and 3 different USB cables (all known to work with multiple devices) but windows never detected them.

**Comment by FeitianSmartcardReader** [comment]
OK please send mail to me hongbin@ftsafe.com, and let us know where you buy from, sales will support you on this, thanks

**Comment by Lectem** [comment]
Closing this in the meantime.
