### ISSUE TITLE
Multiple reader usage on Android 9

### ISSUE THREAD

**Issue by malievci** [FeitianSmartcardReader/FEITIAN_MOBILE_READERS#37]
When multiple readers attached via USB to Android, SCardListReaders method does not return all readers but just one. It is tested under Androidx86 virtual machine with bR301 and bR301 BLE.

Same behaviour also with this method:
String[] names = mFtReader.readerOpen(null);

names containes just one element which is first occurence of usb's.

**Comment by malievci** [comment]
Ok. Then, The SDK document, method names and their explanations are misleading.

**Comment by FeitianSmartcardReader** [comment]
@malievci the latest SDK already support multi-readers on android and iOS too.
