### ISSUE TITLE
Release Notes for iOS Library v3.5.64

### ISSUE THREAD

**Issue by abhishek7kulkarni** [FeitianSmartcardReader/FEITIAN_MOBILE_READERS#38]
What is changed from iOS Library v3.5.61 to v3.5.64?
We are having issues with v3.5.61 where SCardTransmit() hangs for more than 30 seconds for specific addresses on ~5% of the smart cards.
Is this corrected in v3.5.64? What else are the changes implemented?

**Comment by FeitianSmartcardReader** [comment]
@abhishek7kulkarni here is the details:
3.5.64: solved issue with card slot event, got mess with card slot response code with card data before.
3.5.63: open API, you can set timeout with FtSetTimeout, the default time out is 30s
3.5.62: improve the log event 
3.5.61: add new OEM reader support

so I suggest you switch to new lib
