### ISSUE TITLE
Use Feitian library on mac os platform

### ISSUE THREAD

**Issue by Abdelilahskali** [FeitianSmartcardReader/FEITIAN_MOBILE_READERS#42]
Hello Team,
Is there a way to use the library "libiRockey301_3.5.64_Release.a" on mac os platform, it's generated for iOS platform, can you please generate a mac os one ?

```
In /Users/lexpersona/Documents/AppName/shared/resources/libs/feitian/libiRockey301_3.5.64_Release.a(DUKPT.o),
 building for macOS, but linking in object file built for iOS Simulator, file
  '/Users/lexpersona/Documents/AppName/shared/resources/libs/feitian/libiRockey301_3.5.64_Release.a'
   for architecture x86_64
```
Best Regards

**Comment by FeitianSmartcardReader** [comment]
Hi @Abdelilahskali, so far on Apple platform, we only provide iOS SDK for our iOS Reader products.

**Comment by FeitianSmartcardReader** [comment]
Hi @Abdelilahskali , for macOS platform, you can check this repo: https://github.com/FeitianSmartcardReader/R301/tree/master/Demo/macOS, the code is written in C.

**Comment by FeitianSmartcardReader** [comment]
Hi @Abdelilahskali , our team is working on this issue, please check the update later.

**Comment by FeitianSmartcardReader** [comment]
Hi @Abdelilahskali , sorry about linker failed when built for macOS, would you please try the direction in following pic to check if it works?

![Snip20230614_1](https://github.com/FeitianSmartcardReader/FEITIAN_MOBILE_READERS/assets/9547938/4725d0e0-1f88-4024-b35f-098153f7ff18)

For willing to contribute to our project, we very appreciate that.  About the code of repo https://github.com/FeitianSmartcardReader/bR301_iOS/tree/master/libs/source, please wait for our reply later today.

**Comment by FeitianSmartcardReader** [comment]
@Abdelilahskali , about Bluetooth, we do have demo for it, check this archive.
[Readerswiftdemo_202306.zip](https://github.com/FeitianSmartcardReader/FEITIAN_MOBILE_READERS/files/11745558/Readerswiftdemo_202306.zip)
