### ISSUE TITLE
The IOS app doesn't detect the BR301

### ISSUE THREAD

**Issue by farsiss** [FeitianSmartcardReader/FEITIAN_MOBILE_READERS#6]
I've tested your app demo which was available on appstore to see how it works.
But it doesn't detect the BR301 reader. I precise that the BR301 was switched on.

**Comment by FeitianSmartcardReader** [comment]
@farsiss could you please show me your device information? 
check Settings->General->About->scroll down, there has device information under SEID, the OEM version cannot detect by our app.

Thanks and looking forward to your reply,

**Comment by farsiss** [comment]
I've tested on the ipad air 1 but it doesn't have a SEID and on a Iphone s7, here is its SEID : 042D16EB103E80016309018038939903E06186FC5C88ED47

**Comment by FeitianSmartcardReader** [comment]
After you paired with your iOS device, you can find the device information Settings->General->About->scroll down, can you see the device there?
![IMG_2422](https://user-images.githubusercontent.com/9547938/54406001-5d7dff80-4713-11e9-920b-fcbd59374a00.PNG)
![IMG_2422](https://user-images.githubusercontent.com/9547938/54406014-67076780-4713-11e9-8a26-029cb09ba578.PNG)

**Comment by farsiss** [comment]
![image](https://user-images.githubusercontent.com/48514816/54418254-a2e70080-4704-11e9-8d8d-77fdd5b449c4.png)

**Comment by FeitianSmartcardReader** [comment]
@farsiss Your reader is OEM by Zetes, please contact Zetes to have their support, our standard SDK doesn't support, thanks
