### ISSUE TITLE
No issue, hint how quick installl

### ISSUE THREAD

**Issue by AppWerft** [FeitianSmartcardReader/FEITIAN_MOBILE_READERS#8]
http://bit.ly/2GlDj5T

Or direct with QR-Reader, here the address of QR-code:

https://api.qrserver.com/v1/create-qr-code/?data=http%3A%2F%2Fbit.ly%2F2GlDj5T&size=220x220&margin=0

**Comment by FeitianSmartcardReader** [comment]
Will do test tomorrow. Thanks for your feedback.

**Comment by FeitianSmartcardReader** [comment]
Got you, thanks for sharing,
